name = "CosimaModels"
uuid = "3fe76b4a-150b-43fb-a44b-d0b5367c8019"
authors = ["Grzegorz Orzechowski <2590699+gorzech@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Cosima = "5277e416-3218-405d-896e-75d2efdc383a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
